trigger:
- master
- releases/*

jobs:

# All tasks on Windows
- job: build_all_windows
  displayName: Build all tasks (Windows)
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      os: Windows_NT

# Publish on Windows
- job: publish_windows
  displayName: Publish
  dependsOn: 
  - build_all_windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: ci/publish-steps.yml

# Single task
- job: buildSingle
  displayName: Build single task
  condition: and(succeeded(), variables.task)
  steps:
  - template: ci/build-single-steps.yml
